In [1]:
import os 
import glob

import xarray as xr

import matplotlib.pyplot as plt 
%matplotlib inline

In [2]:
path = '/home/hanna/lagrings/results/stats/monthly_mean/'

In [3]:
files = glob.glob(path+'*.nc')

In [4]:
files

['/home/hanna/lagrings/results/stats/monthly_mean/monthly_means.nc',
 '/home/hanna/lagrings/results/stats/monthly_mean/correlation_sp.nc',
 '/home/hanna/lagrings/results/stats/monthly_mean/correlation.nc',
 '/home/hanna/lagrings/results/stats/monthly_mean/monthly_means_updated.nc',
 '/home/hanna/lagrings/results/stats/monthly_mean/correlation_updated.nc',
 '/home/hanna/lagrings/results/stats/monthly_mean/monthly_means_updated_2.nc']

In [5]:
data = xr.open_dataset('/home/hanna/lagrings/results/stats/monthly_mean/monthly_means_updated_2.nc')

In [6]:
data

<xarray.Dataset>
Dimensions:   (date_q: 180, date_r: 180, date_sp: 180, date_t2m: 180, date_tcc: 177, land_q: 180, land_r: 180, land_sp: 180, land_t2m: 180, land_tcc: 177, q: 180, r: 180, sea_q: 180, sea_r: 180, sea_sp: 180, sea_t2m: 180, sea_tcc: 177, sp: 180, t2m: 180, tcc: 177)
Coordinates:
  * r         (r) float32 73.3469 69.28387 68.77819 ... 73.89609 74.36421
  * land_r    (land_r) float64 74.04 67.37 64.93 62.91 ... 65.92 74.57 74.31
  * sea_r     (sea_r) float64 72.53 71.52 73.27 72.81 ... 74.59 73.11 74.43
  * date_r    (date_r) datetime64[ns] 2004-01-01 2004-02-01 ... 2018-12-01
  * q         (q) float32 0.0052385144 0.005055673 ... 0.0070216656 0.0058911303
  * land_q    (land_q) float64 0.004256 0.004232 0.004638 ... 0.006077 0.004843
  * sea_q     (sea_q) float64 0.006384 0.006016 0.006308 ... 0.008123 0.007113
  * date_q    (date_q) datetime64[ns] 2004-01-01 2004-02-01 ... 2018-12-01
  * t2m       (t2m) float32 281.83633 282.70535 284.13245 ... 286.3971 283.75046
  * land_t2m  (land_t2m) float64 278.1 280.0 282.4 286.1 ... 288.8 283.5 280.1
  * sea_t2m   (sea_t2m) float64 286.2 285.8 286.1 287.4 ... 292.5 289.7 288.0
  * date_t2m  (date_t2m) datetime64[ns] 2004-01-01 2004-02-01 ... 2018-12-01
  * sp        (sp) float32 98225.94 98634.56 98678.89 ... 98291.664 98897.7
  * land_sp   (land_sp) float64 9.54e+04 9.581e+04 ... 9.566e+04 9.614e+04
  * sea_sp    (sea_sp) float64 1.015e+05 1.019e+05 ... 1.014e+05 1.021e+05
  * date_sp   (date_sp) datetime64[ns] 2004-01-01 2004-02-01 ... 2018-12-01
  * tcc       (tcc) float64 0.4815 0.4366 0.3218 0.2604 ... 0.5275 0.6138 0.5871
  * land_tcc  (land_tcc) float64 0.7052 0.6925 0.6452 ... 0.7014 0.7491 0.7437
  * sea_tcc   (sea_tcc) float64 0.7379 0.7237 0.6857 ... 0.7353 0.7714 0.7611
  * date_tcc  (date_tcc) datetime64[ns] 2004-04-01 2004-05-01 ... 2018-12-01
Data variables:
    *empty*

In [7]:
data = xr.open_dataset('/home/hanna/lagrings/results/stats/monthly_mean/monthly_means_updated.nc')

In [8]:
data

<xarray.Dataset>
Dimensions:   (date_q: 180, date_r: 180, date_sp: 180, date_t2m: 180, date_tcc: 177, land_q: 180, land_r: 180, land_sp: 180, land_t2m: 180, land_tcc: 177, q: 180, r: 180, sea_q: 180, sea_r: 180, sea_sp: 180, sea_t2m: 180, sea_tcc: 177, sp: 180, t2m: 180, tcc: 177)
Coordinates:
  * r         (r) float32 73.3469 69.28387 68.77819 ... 73.89609 74.36421
  * land_r    (land_r) float64 74.04 67.37 64.93 62.91 ... 65.92 74.57 74.31
  * sea_r     (sea_r) float64 72.53 71.52 73.27 72.81 ... 74.59 73.11 74.43
  * date_r    (date_r) datetime64[ns] 2004-01-01 2004-02-01 ... 2018-12-01
  * q         (q) float32 0.0052385144 0.005055673 ... 0.0070216656 0.0058911303
  * land_q    (land_q) float64 0.004256 0.004232 0.004638 ... 0.006077 0.004843
  * sea_q     (sea_q) float64 0.006384 0.006016 0.006308 ... 0.008123 0.007113
  * date_q    (date_q) datetime64[ns] 2004-01-01 2004-02-01 ... 2018-12-01
  * t2m       (t2m) float32 281.83633 282.70535 284.13245 ... 286.3971 283.75046
  * land_t2m  (land_t2m) float64 278.1 280.0 282.4 286.1 ... 288.8 283.5 280.1
  * sea_t2m   (sea_t2m) float64 286.2 285.8 286.1 287.4 ... 292.5 289.7 288.0
  * date_t2m  (date_t2m) datetime64[ns] 2004-01-01 2004-02-01 ... 2018-12-01
  * sp        (sp) float32 98225.94 98634.56 98678.89 ... 98291.664 98897.7
  * land_sp   (land_sp) float64 9.54e+04 9.581e+04 ... 9.566e+04 9.614e+04
  * sea_sp    (sea_sp) float64 1.015e+05 1.019e+05 ... 1.014e+05 1.021e+05
  * date_sp   (date_sp) datetime64[ns] 2004-01-01 2004-02-01 ... 2018-12-01
  * tcc       (tcc) float64 0.4815 0.4366 0.3218 0.2604 ... 0.5275 0.6138 0.5871
  * land_tcc  (land_tcc) float64 0.7052 0.6925 0.6452 ... 0.7014 0.7491 0.7437
  * sea_tcc   (sea_tcc) float64 0.7379 0.7237 0.6857 ... 0.7353 0.7714 0.7611
  * date_tcc  (date_tcc) datetime64[ns] 2004-04-01 2004-05-01 ... 2018-12-01
Data variables:
    *empty*

# Check filter 

In [15]:

df_return = data.mean(['latitude', 'longitude']).copy()

for var in VARIABLES:
    fs = Filter('sea').set_data(data, variable = var)
    fl = Filter('land').set_data(data, variable = var)

    df_return['land_{}'.format(var)] = fl.get_mean()
    df_return['sea_{}'.format(var)]  = fs.get_mean()


In [21]:
from sclouds.helpers import VARIABLES
from sclouds.io.filter import Filter
from sclouds.io.utils import get_xarray_dataset_for_period

In [23]:
data = get_xarray_dataset_for_period(start = '2012-07-01', stop  = '2012-07-07')


 searchers for files

 Searching in directory /home/hanna/lagrings/ERA5_monthly/ 

Num files 5


/home/hanna/MS/sclouds/helpers.py:93: FutureWarning: In xarray version 0.15 the default behaviour of `open_mfdataset`
will change. To retain the existing behavior, pass
combine='nested'. To use future default behavior, pass
combine='by_coords'. See
http://xarray.pydata.org/en/stable/combining.html#combining-multi

  return xr.open_mfdataset(files, compat='no_conflicts') # , join='outer'
/home/hanna/anaconda3/envs/final/lib/python3.7/site-packages/xarray/backends/api.py:941: FutureWarning: The datasets supplied have global dimension coordinates. You may want
to use the new `combine_by_coords` function (or the
`combine='by_coords'` option to `open_mfdataset`) to order the datasets
before concatenation. Alternatively, to continue concatenating based
on the order the datasets are supplied in future, please use the new
`combine_nested` function (or the `combine='nested'` option to
open_mfdataset).The datasets supplied require both concatenation and merging. From
xarray version 0.15 this wil

In [31]:
mean = data['tcc'].copy().mean(['latitude', 'longitude']).values

In [63]:
fland = Filter('land').set_data(data.copy(), variable = 'tcc')

In [36]:
fsea = Filter('sea').set_data(data.copy(), variable = 'tcc')

In [64]:
da = fland.get_filtered_data()['filtered']

In [65]:
da

<xarray.DataArray 'filtered' (time: 168, latitude: 81, longitude: 161)>
array([[[0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        ...,
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ]],

       [[0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        ...,
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ]],

       [[0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        ...,
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ]],

       ...,

       [[0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        ...,
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ]],

       [[0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        ...,
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.13819899,
         0.22906786, 0.50311685],
        [0.        , 0.        , 0.        , ..., 0.66380298,
         0.30682596, 0.41154064]],

       [[0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        ...,
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.08804979, 0.        ],
        [0.        , 0.        , 0.        , ..., 0.48954309,
         0.51354479, 0.3804391 ]]])
Coordinates:
  * latitude       (latitude) float64 30.0 30.25 30.5 30.75 ... 49.5 49.75 50.0
  * time           (time) datetime64[ns] 2012-07-01 ... 2012-07-07T23:00:00
  * longitude      (longitude) float64 -15.0 -14.75 -14.5 ... 24.5 24.75 25.0
    number         int64 0
    step           timedelta64[ns] 00:00:00
    isobaricInhPa  int64 1000
    valid_time     (t

In [66]:
import numpy as np

In [67]:
matrix = da.values
matrix[matrix == 0.0] = np.nan

In [68]:
#matrix

In [69]:
tm = np.nanmean(matrix, axis=(1, 2))

In [70]:
tm

array([0.60431504, 0.60712449, 0.61355384, 0.60418142, 0.58621085,
       0.6621359 , 0.63276396, 0.62481066, 0.59933712, 0.59124666,
       0.60362334, 0.57996412, 0.58088263, 0.59133224, 0.61956552,
       0.6380085 , 0.66443494, 0.65887532, 0.69580664, 0.66741418,
       0.68598736, 0.68078231, 0.68804331, 0.68528293, 0.66051932,
       0.65724215, 0.64196587, 0.63184011, 0.62597555, 0.67241921,
       0.66263143, 0.66158386, 0.65768988, 0.65275238, 0.66135099,
       0.65148135, 0.65551431, 0.66631147, 0.672448  , 0.67731104,
       0.69786944, 0.72105831, 0.70736348, 0.68362424, 0.67480969,
       0.6507079 , 0.62438468, 0.60971251, 0.6217888 , 0.62303057,
       0.61173682, 0.62172979, 0.60201719, 0.61031874, 0.62451894,
       0.62144538, 0.62314411, 0.60644834, 0.60019677, 0.60008237,
       0.63230545, 0.66124511, 0.681527  , 0.67915429, 0.69284366,
       0.71350876, 0.70846879, 0.73057729, 0.72018576, 0.70025797,
       0.68215644, 0.63530173, 0.60029795, 0.57318148, 0.56648

In [71]:
mean = np.true_divide(da.sum(['latitude', 'longitude']),
                        (da!=0.0).sum(['latitude', 'longitude']))

In [48]:
mean

<xarray.DataArray 'filtered' (time: 168)>
array([0.53917446, 0.52885755, 0.5057251 , 0.49163754, 0.49784291,
       0.56266767, 0.63790747, 0.63730625, 0.58400579, 0.57460872,
       0.55589045, 0.53950098, 0.53531166, 0.54395597, 0.55878649,
       0.55831629, 0.59922584, 0.64851856, 0.70659922, 0.66637066,
       0.65780152, 0.64835865, 0.64587666, 0.63137145, 0.61608356,
       0.60037381, 0.60145244, 0.58125886, 0.56816541, 0.62555423,
       0.65605182, 0.67918403, 0.64531112, 0.62690909, 0.59867746,
       0.59215262, 0.60297981, 0.61352942, 0.61353166, 0.62757754,
       0.64060172, 0.68263535, 0.68018443, 0.66341692, 0.65978378,
       0.63943594, 0.61638459, 0.60141195, 0.59280228, 0.59702669,
       0.60100605, 0.59671572, 0.5981798 , 0.62171147, 0.67988168,
       0.72508032, 0.70013912, 0.69651297, 0.67828107, 0.67298861,
       0.67701181, 0.68749062, 0.7038994 , 0.71719589, 0.72878385,
       0.75555118, 0.77355881, 0.77925084, 0.74028565, 0.73187306,
       0.73452699, 0.73123591, 0.72926769, 0.7196385 , 0.70611778,
       0.69932715, 0.68994027, 0.69735621, 0.74455164, 0.75004924,
       0.72836708, 0.72054464, 0.69647786, 0.6818728 , 0.69153215,
       0.69523198, 0.69606981, 0.70622809, 0.7211083 , 0.74300262,
       0.72824852, 0.73708351, 0.71109838, 0.71120135, 0.70357114,
       0.70788483, 0.72269722, 0.70394242, 0.70200095, 0.69489684,
       0.70758997, 0.69208739, 0.71964614, 0.73237437, 0.72200019,
       0.71070797, 0.6911313 , 0.67565747, 0.68362183, 0.68754886,
       0.69351252, 0.69069419, 0.69596774, 0.72742835, 0.72779955,
       0.72522234, 0.70003702, 0.67994405, 0.65988119, 0.6614903 ,
       0.6565448 , 0.65847718, 0.65015961, 0.64387028, 0.63898881,
       0.65706225, 0.67575744, 0.69529912, 0.67874096, 0.67651585,
       0.67924226, 0.67828141, 0.67174279, 0.68448086, 0.70650568,
       0.71770455, 0.7363227 , 0.73228128, 0.76008999, 0.76044121,
       0.72290443, 0.71506815, 0.697679  , 0.66433111, 0.64568603,
       0.64203335, 0.629116  , 0.62070448, 0.64148486, 0.67687907,
       0.69800994, 0.71699977, 0.68597879, 0.66645636, 0.64049253,
       0.61884786, 0.62343732, 0.62268698, 0.62269576, 0.62430725,
       0.64924677, 0.7136478 , 0.75085379, 0.70297471, 0.66551172,
       0.6653033 , 0.65679732, 0.65677743])
Coordinates:
  * time           (time) datetime64[ns] 2012-07-01 ... 2012-07-07T23:00:00
    number         int64 0
    step           timedelta64[ns] 00:00:00
    isobaricInhPa  int64 1000
    valid_time     (time) datetime64[ns] dask.array<chunksize=(168,), meta=np.ndarray>
    surface        int64 0

In [35]:
fland = Filter('land').set_data(data.copy(), variable = 'tcc')

In [24]:
#df = filter_data_in_period(start = '2012-07-01', stop  = '2012-07-07')

In [17]:
df

<xarray.Dataset>
Dimensions:        (time: 168)
Coordinates:
  * time           (time) datetime64[ns] 2012-07-01 ... 2012-07-07T23:00:00
    number         int64 0
    step           timedelta64[ns] 00:00:00
    isobaricInhPa  int64 1000
    valid_time     (time) datetime64[ns] dask.array<chunksize=(168,), meta=np.ndarray>
    surface        int64 0
Data variables:
    tcc            (time) float64 dask.array<chunksize=(168,), meta=np.ndarray>
    nr_nans        (time) float64 dask.array<chunksize=(168,), meta=np.ndarray>
    q              (time) float32 dask.array<chunksize=(168,), meta=np.ndarray>
    r              (time) float32 dask.array<chunksize=(168,), meta=np.ndarray>
    sp             (time) float32 dask.array<chunksize=(168,), meta=np.ndarray>
    t2m            (time) float32 dask.array<chunksize=(168,), meta=np.ndarray>
    land_t2m       float64 297.2
    sea_t2m        float64 295.6
    land_sp        float64 9.741e+04
    sea_sp         float64 9.903e+04
    land_q         float64 0.01001
    sea_q          float64 0.01088
    land_r         float64 59.54
    sea_r          float64 68.87
    land_tcc       float64 0.6404
    sea_tcc        float64 0.6694

In [18]:
df['tcc'].values

array([0.29802086, 0.30834166, 0.30941782, 0.29590112, 0.32040889,
       0.38468987, 0.36879142, 0.33479504, 0.29764591, 0.29664283,
       0.30512614, 0.30741352, 0.32087757, 0.31657884, 0.32098921,
       0.33193738, 0.36743683, 0.43698738, 0.44195611, 0.41340044,
       0.42226957, 0.41373382, 0.40434599, 0.39069205, 0.37006279,
       0.38179842, 0.37620955, 0.35322227, 0.36130271, 0.42493055,
       0.39698373, 0.3760651 , 0.34746027, 0.33692858, 0.34173623,
       0.34964847, 0.36519601, 0.36897071, 0.37196991, 0.37824802,
       0.39717279, 0.47459663, 0.46287931, 0.44151182, 0.42625348,
       0.40315663, 0.3764032 , 0.35638562, 0.34681395, 0.3619869 ,
       0.35637017, 0.34404344, 0.34892408, 0.39444088, 0.3915437 ,
       0.38071118, 0.34438169, 0.3325223 , 0.34291161, 0.36018023,
       0.39568402, 0.40612247, 0.41953511, 0.43028642, 0.44937597,
       0.52649738, 0.52263706, 0.53266062, 0.507633  , 0.49405448,
       0.47209169, 0.44276784, 0.40591556, 0.40690909, 0.40263

In [19]:
df['land_tcc'].values

array(0.64044819)

In [20]:
df['sea_tcc'].values

array(0.66937302)